config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  get 'sessions/new' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'users/new'
  post 'welcome/index' => 'sessions#create'


  resources :users do
    resources :cities
  end
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, length: { minimum: 8, too_short: "%{count} characters is the minimum required." }
  validates_uniqueness_of :username
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:index, :edit, :new, :destroy]
  # GET /cities
  # GET /cities.json
  def index
    @cities = @current_user.cities
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = current_user.cities.build(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to user_cities_path(current_user), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to user_cities_path, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to user_cities_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    def current_user
      @current_user = User.find(params[:user_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
  end

  def create
    # puts "password = #{params[:password]}"
    @user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_cities_path(@user)
    else
      redirect_to root_path, notice: "Your username and/or password are incorrect!"
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to user_cities_path(@user), notice: 'Created user'
    else
      render :new
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
  
  def get_weather(city)
    response = HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{city}&units=imperial&appid=#{ENV['OPENWEATHER_KEY']}")
    return response.parsed_response
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    User.find(session[@current_user.id])
  end
end

app/views/cities/_form.html.erb
<%= form_for([current_user, @city], local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :city_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', city: @city %> |
<%= link_to 'Back', user_cities_path %>

app/views/cities/index.html.erb
<div class="container">
  <h1>Cities</h1>
  <table class="table-condensed table-hover col-xs-12 welcome-table">
    <thead>
      <tr>
        <th>City Name</th>
        <th colspan="3"></th>
        <th>Temp. (f)</th>
      </tr>
    </thead>

    <tbody>
      <p id="notice"><%= notice %></p>

      <h1 class="welcome-back">Welcome back, <%= current_user.username %>!</h1>
      <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <%  main = get_weather(city.name) %>
        <td><%= main["main"]["temp"] %></td>
        <td><%= main["weather"][0]["main"]%></td>
        <td><%= main["weather"][0]["description"] %></td>
        <td><%= link_to 'Show', user_cities_path %></td>
        <td><%= link_to 'Edit', edit_user_city_path(current_user.id, city.id) %></td>
        <td><%= link_to 'Destroy', user_city_path(current_user.id, city.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New City', new_user_city_path(current_user.id) %>
<br>
<%= link_to 'Logout', logout_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', user_cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Favorite Forecast</title>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= content_for :body_class %>">
  <%= yield %>
</body>
</html>

app/views/users/_new.html.erb
<div class="modal fade" id="myModal123" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header views">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Join Favorite Forecast!</h4>
      </div>
      <div class="modal-body">

        <h1>Sign Up</h1>
        <%= form_with(model: @user, url: users_path(@user)) do |f| %>
        <p>
          <%= f.label :username %>
          <%= f.text_field :username %>
        </p>
        <p>
          <%= f.label :password %>
          <%= f.password_field :password %>
        </p>
        <p>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </p>

        <p>
          <div class="logger"> <%= f.submit 'Join', :id =>'Login'%></div>
        </p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with(model: @user, url: users_path(@user)) do |f| %>
<p>
<%= f.label :username %>
  <%= f.text_field :username %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %></h1>

app/views/welcome/index.html.erb
<% content_for :body_class, 'class1' %>

<button class="button" type="button" name="button" id="Login"><%= link_to 'Sign Up', '#', :'data-toggle'=> "modal", :'data-target'=>"#myModal123" %></button>
<button class="button" type="button" name="button" id="Login"><%= link_to 'Login', '#', :'data-toggle'=> "modal", :'data-target'=>"#loginModal" %></button>

<%= render partial: 'sessions/login' %>
<%= render partial: "users/new" %>